-- PGY90 Health Coach Supabase / PostgreSQL schema
-- Phase 1: schema only, no real data included.
-- Apply manually in the Supabase SQL editor after review.
--
-- Notes:
-- - This schema mirrors the current SQLite tables conservatively.
-- - Current app data isolation still uses person_name.
-- - Supabase Auth is not integrated in this phase.
-- - RLS policies are not enabled in this phase.
-- - Data import from SQLite CSV exports belongs to Phase 2.
-- - Legacy SQLite table coach_profile has 0 rows and is not migrated as a
--   formal Supabase table. Use coach_profiles instead.

create table if not exists public.people (
    person_name text primary key,
    created_at timestamptz not null
);

create table if not exists public.app_users (
    person_name text primary key,
    password_salt text not null,
    password_hash text not null,
    created_at timestamptz not null
);

create table if not exists public.daily_logs (
    person_name text not null default '我',
    log_date date not null,
    weight_kg double precision,
    body_fat_percent double precision,
    waist_cm double precision,
    sleep_hours double precision,
    sleep_quality integer,
    food_category text,
    food_notes text,
    breakfast_category text,
    breakfast_notes text,
    lunch_category text,
    lunch_notes text,
    dinner_category text,
    dinner_notes text,
    snack_notes text,
    workout_type text,
    workout_minutes integer,
    avg_heart_rate integer,
    max_heart_rate integer,
    active_calories integer,
    distance_km double precision,
    rpe integer,
    discomfort_notes text,
    workout_notes text,
    rehab_done boolean default false,
    rehab_type text,
    rehab_notes text,
    notes text,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    systolic_bp integer,
    diastolic_bp integer,
    pulse_bpm integer,
    primary key (person_name, log_date)
);

create table if not exists public.meal_logs (
    id bigint generated by default as identity primary key,
    log_date date not null,
    meal_type text not null,
    description text not null,
    calories integer,
    protein_g double precision,
    fiber_g double precision,
    carbs_g double precision,
    fat_g double precision,
    confidence text not null,
    created_at timestamptz not null,
    person_name text not null default '我'
);

create table if not exists public.favorite_meals (
    id bigint generated by default as identity primary key,
    person_name text not null,
    name text not null,
    meal_type text not null,
    description text not null,
    calories integer,
    protein_g double precision,
    fiber_g double precision,
    carbs_g double precision,
    fat_g double precision,
    created_at timestamptz not null,
    updated_at timestamptz not null,
    unique (person_name, name)
);

create table if not exists public.coach_profiles (
    person_name text primary key,
    goal text not null,
    current_weight_kg double precision,
    daily_calorie_target integer,
    protein_target_g integer,
    fiber_target_g integer,
    preferences text,
    updated_at timestamptz not null,
    height_cm double precision,
    target_weight_kg double precision,
    target_body_fat_min double precision,
    target_body_fat_max double precision,
    gender text,
    birth_year integer,
    activity_level text,
    health_limitations text
);

create table if not exists public.weekly_reports (
    person_name text not null default '我',
    week_start date not null,
    week_end date not null,
    summary text not null,
    generated_at timestamptz not null,
    primary key (person_name, week_start)
);

-- Conservative indexes for current query patterns.
-- Primary keys already index people.person_name, app_users.person_name,
-- coach_profiles.person_name, daily_logs(person_name, log_date), and
-- weekly_reports(person_name, week_start).

create index if not exists idx_people_created_at
    on public.people (created_at);

create index if not exists idx_app_users_created_at
    on public.app_users (created_at);

create index if not exists idx_daily_logs_log_date
    on public.daily_logs (log_date);

create index if not exists idx_daily_logs_updated_at
    on public.daily_logs (updated_at);

create index if not exists idx_meal_logs_person_date
    on public.meal_logs (person_name, log_date);

create index if not exists idx_meal_logs_log_date
    on public.meal_logs (log_date);

create index if not exists idx_meal_logs_created_at
    on public.meal_logs (created_at);

create index if not exists idx_favorite_meals_person_name
    on public.favorite_meals (person_name, name);

create index if not exists idx_favorite_meals_updated_at
    on public.favorite_meals (updated_at);

create index if not exists idx_coach_profiles_updated_at
    on public.coach_profiles (updated_at);

create index if not exists idx_weekly_reports_week_end
    on public.weekly_reports (week_end);

create index if not exists idx_weekly_reports_generated_at
    on public.weekly_reports (generated_at);

-- TODO before production cutover:
-- - Verify CSV import casts for date, timestamptz, and rehab_done boolean.
-- - Decide whether to add foreign keys from person_name to people.person_name
--   after validating all imported records.
-- - Design and enable RLS policies after app-level Supabase access patterns are
--   finalized.
-- - Supabase Auth integration is intentionally out of scope for Phase 1.
